on: 
  push:
    branches:
      - master
      - develop

jobs:
  release-on-push:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Bump version major
      id: bump_tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: major
        RELEASE_BRANCHES : master
        DRY_RUN : true
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@master"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Next Tag
      run: echo ${{ steps.bump_tag.outputs.new_tag }}
    - name: Tag
      run: echo ${{ steps.bump_tag.outputs.tag }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.bump_tag.outputs.new_tag }}
        release_name: Release ${{ steps.bump_tag.outputs.new_tag }}
        draft: false
        prerelease: false
    

  prerelease-on-push:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Bump version minor
      if: github.ref == 'refs/heads/develop'
      id: bump_tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: minor
        RELEASE_BRANCHES : develop
        DRY_RUN : true
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@master"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Next Tag
      run: echo ${{ steps.bump_tag.outputs.new_tag }}
    - name: Tag
      run: echo ${{ steps.bump_tag.outputs.tag }}
    - name: Create Pre-Release
      id: create_prerelease
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.bump_tag.outputs.new_tag }}
        release_name: ${{ steps.bump_tag.outputs.new_tag }}
        draft: false
        prerelease: true
